# Categorization of the candidates in the Hadronic RDs MC samples

In [1]:
import ROOT
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
import json
from XRootD import client
from IPython.display import display, HTML
pd.options.display.latex.repr = True
%matplotlib inline

Welcome to JupyROOT 6.28/00

## List of event types and utility methods

In [2]:
## Should get this from the config
#data_prefix = "root://eoslhcb.cern.ch//eos/lhcb/wg/semileptonic/RDsHad/AP/pidgen_merged/"
data_prefix = "root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged"

# eventtypes for which there is no right sign/wrong sign samples
eventtypes_nosign = [ "13763200", "13266069", "13863401", "11266009"]

# Inclusive MC event types
eventtypes_inclMC = [ "23903003", "23903000",]

# Inclusive MC event types
eventtypes_signal = [ "13563002", ]

# eventtypes for which we have right sign/wrong sign samples
eventtypes_sign = eventtypes_signal + eventtypes_inclMC

# other attributes of the dataset
polarities = ["magup", "magdown"]
datatypes = ["2012"]
signs = ["ws", "rs"]

def get_filenames(datatype, eventtype, sign):
        filenames = [ f"{data_prefix}/rds_categ_{datatype}_{eventtype}_{polarity}_{sign}.root" 
                      for polarity in polarities ]
        return filenames

In [3]:
# Loading the list of categories 
metadata_filename =  data_prefix + "/rds_categ_metadata_2012_23903003_magdown_rs.json"
with client.File() as f:
    f.open(metadata_filename)
    buffer = f.read()
    metadata = json.loads(buffer[1])
detailed_categories_map = metadata["detailed_categories"]
simple_categories_map = metadata["simple_categories"]

ValueError: I/O operation on closed file

In [18]:
def mygroupby(d, groupbycols):
    g = d.groupby(groupbycols).size().reset_index(name='count').sort_values([ 'count'], ascending=False).reset_index(drop=True)
    g["Percentage"] = g.apply(lambda row: 100 * row["count"]/d.shape[0], axis=1)
    g["cumulative %"] = g["Percentage"].cumsum(axis = 0)
    return g

In [19]:
filter_vars = [ "simplified", "category"]
plot_vars = [ "B_Y_SEP", "B_M", "Y_M", "q2_2", "tauY_2" ]

In [20]:
def get_dataframe(datatype, eventtype, sign, filter=None):
    filenames =  get_filenames(datatype, eventtype, sign)
    print(filenames)
    rdf = ROOT.RDataFrame("DecayTree", filenames)
    if filter is not None:
        rdf = rdf.Filter(filter)
    df = pd.DataFrame(rdf.Cache(plot_vars + filter_vars).AsNumpy())
    return df

In [21]:
def print_stats(datatype, eventtype, sign, filter=None):
    df = get_dataframe(datatype, eventtype, sign, filter)
    df["category name"] = df.apply(lambda row: detailed_categories_map[str(int(row['category']))], axis=1)
    df["simplified category"] = df.apply(lambda row: simple_categories_map[str(int(row['simplified']))], axis=1)
    g = mygroupby(df, ['category name'])
    display(HTML(g.to_html()))
    gs = mygroupby(df, ['simplified category'])
    display(HTML(gs.to_html()))

## Statistics for  23903000 (Inclusive MC) after filtering

In [22]:
print_stats("2012", "23903000", "rs")

['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_23903000_magup_rs.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_23903000_magdown_rs.root']

## Statistics for  23903003 (Inclusive MC) after filtering

In [23]:
print_stats("2012", "23903003", "rs")

['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_23903003_magup_rs.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_23903003_magdown_rs.root']

## Statistics for signal 13563002

### Overall sample

In [24]:
print_stats("2012", "13563002", "rs")

['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magup_rs.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magdown_rs.root']

### True Taus only

In [25]:
filter = "(Xc_BKGCAT== 0 ) &&  Y_BKGCAT==50 && B_BKGCAT==50 && abs(p1_fromXc_TRUEID)==321 && abs(p2_fromXc_TRUEID)==321 && abs(p3_fromXc_TRUEID)==211 && abs(p1_fromY_TRUEID)+abs(p2_fromY_TRUEID)+abs(p3_fromY_TRUEID)==3*211 "
print_stats("2012", "13563002", "rs", filter=filter)

['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magup_rs.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magdown_rs.root']

### Wrong sign sample

In [26]:
print_stats("2012", "13563002", "ws")

['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magup_ws.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13563002_magdown_ws.root']

## Categorization of other samples

In [27]:
for e in eventtypes_nosign:
    print(f"== File for eventype {e}")
    print_stats("2012", e, "None")

== File for eventype 13763200
['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13763200_magup_None.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13763200_magdown_None.root']

== File for eventype 13266069
['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13266069_magup_None.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13266069_magdown_None.root']

== File for eventype 13863401
['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13863401_magup_None.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_13863401_magdown_None.root']

== File for eventype 11266009
['root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_11266009_magup_None.root', 'root://eoslhcb.cern.ch//eos/lhcb/user/b/bcouturi/rds/pidgen_merged/rds_categ_2012_11266009_magdown_None.root']